import {
  PayCircleOutlined,
  ShoppingCartOutlined,
  MessageOutlined,
  TeamOutlined,
  UserOutlined,
  DashboardOutlined,
  ApiOutlined,
  CameraOutlined,
  EditOutlined,
  CodeOutlined,
  LineOutlined,
  BarChartOutlined,
  AreaChartOutlined,
  AccountBookOutlined,
  MoneyCollectOutlined,
  PropertySafetyOutlined,
  RedEnvelopeOutlined,
  TransactionOutlined
} from '@ant-design/icons'

export default {
  'pay-circle-o': <PayCircleOutlined />,
  'shopping-cart': <ShoppingCartOutlined />,
  'camera-o': <CameraOutlined />,
  'line-chart': <LineOutlined />,
  'code-o': <CodeOutlined />,
  'area-chart': <AreaChartOutlined />,
  'bar-chart': <BarChartOutlined />,
  message: <MessageOutlined />,
  team: <TeamOutlined />,
  dashboard: <DashboardOutlined />,
  user: <UserOutlined />,
  api: <ApiOutlined />,
  edit: <EditOutlined />,
  采购管理: <AccountBookOutlined />,
  原材料管理: <MoneyCollectOutlined />,
  薪资发放: <PayCircleOutlined />,
  月营业额: <PropertySafetyOutlined />,
  库存盘点: <RedEnvelopeOutlined />,
  社保医疗: <TransactionOutlined />,
  毛利统计: <PayCircleOutlined />
}
